### ISSUE TITLE
In stim library, add ability to make a copy of a map

### ISSUE THREAD

**Issue by adamltaylor** [JaneliaSciComp/Wavesurfer#121]
User could then modify the new map, including renaming it.  (This was requested today.)

**Comment by adamltaylor** [comment]
Maybe also implement a similar copy functionality for stimuli, sequences.

**Comment by davidackerman** [comment]
Ability to duplicate maps has been implemented.

**Comment by davidackerman** [comment]
Closed in the develop branch as of commit 47b2e4da8094b9ac8cc7e2f384fa143874915a9a
