### ISSUE TITLE
Should pick open TCP ports, instead of using fixed ones

### ISSUE THREAD

**Issue by adamltaylor** [JaneliaSciComp/Wavesurfer#140]
Currently (WS 0.91), we use fixed TCP ports for interprocess communication: 8081, 8082, 8083.  It would be better to let ZMQ pick the port for us from the list of free ports, and then pass those port numbers to the satellites when we start them.

In particular, there's a notification program that gets installed on all IT-provisioned Windows boxes (as of 02/2016) that uses 8082, which causes WS to error on startup.

**Comment by adamltaylor** [comment]
The notification program is called "InformaCast Desktop Notifier".

**Comment by davidackerman** [comment]
Now automatically binds to free ports.
