### ISSUE TITLE
Acquisition at 50 kHz doesn't work well

### ISSUE THREAD

**Issue by adamltaylor** [JaneliaSciComp/Wavesurfer#142]
Pierre reports:

2) The few times I have tried acquiring at 50khz, it has been a problem.
This may be because I set the acquisition at 50khz while keeping the
output channel signals at 20khz. I¹ll look into this more next week.

**Comment by adamltaylor** [comment]
This is in 0.9 beta 11.

**Comment by adamltaylor** [comment]
Seems likely that this is a hardware problem (trying to use a too-slow card).  I can't repro it with a 6351 (works fine with all channels).  Should try it on a 6341, doing all channels at 50 kHz.  That should work, but with less headroom than with a 6351.

**Comment by davidackerman** [comment]
Tested it on a 6341, with all channels at 50 kHz (with and without stimulation at 20 kHz), with no issues.
