### ISSUE TITLE
possible bugs with NI-DAQmx 14.0

### ISSUE THREAD

**Issue by bjarthur** [JaneliaSciComp/Wavesurfer#15]
>> ws.dabs.ni.daqmx.System

You cannot set the read-only property 'cancelConstruct' of System.

Error in ws.most.APIWrapper (line 171)
                obj.cancelConstruct = true;

Error in ws.dabs.ni.daqmx.private.DAQmxClass (line 1)
classdef DAQmxClass < ws.most.APIWrapper & ws.most.PDEPPropDynamic

Error in ws.dabs.ni.daqmx.System (line 28)
        function obj = System(varargin)
 
>> ver
----------------------------------------------------------------------------------------------------
MATLAB Version: 8.3.0.532 (R2014a)
MATLAB License Number: 832378
Operating System: Microsoft Windows 7 Professional  Version 6.1 (Build 7601: Service Pack 1)
Java Version: Java 1.7.0_11-b21 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
----------------------------------------------------------------------------------------------------
MATLAB                                                Version 8.3        (R2014a)
Bioinformatics Toolbox                                Version 4.4        (R2014a)
Curve Fitting Toolbox                                 Version 3.4.1      (R2014a)
Data Acquisition Toolbox                              Version 3.5        (R2014a)
Image Processing Toolbox                              Version 9.0        (R2014a)
Mapping Toolbox                                       Version 4.0.1      (R2014a)
Parallel Computing Toolbox                            Version 6.4        (R2014a)
Signal Processing Toolbox                             Version 6.21       (R2014a)
Statistics Toolbox                                    Version 9.0        (R2014a)
Wavelet Toolbox                                       Version 4.13       (R2014a)

**Comment by adamltaylor** [comment]
http://jira.vidriotechnologies.com/browse/SIDEV-112

**Comment by adamltaylor** [comment]
This happens b/c DABS does not support NI DAQmx drivers more recent than version 9.8.x.  We're going to let the Vidrio guys fix this.

**Comment by bjarthur** [comment]
actually, after downgrading to nidaqmx 9.8 the exact same error still occurred.  problem was that wavesurfer was installed in an NFS mounted fileshare.

**Comment by adamltaylor** [comment]
Huh.  I'm surprised that that mattered...  So it's working now?

I'm getting a safety inspection on my car, so I'll probably be in around
noon.

Adam

-----
On Thursday, March 19, 2015, Ben Arthur <notifications@github.com> wrote:

> actually, after downgrading to nidaqmx 9.8 the exact same error still
> occurred. problem was that wavesurfer was installed in an NFS mounted
> fileshare.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JaneliaSciComp/Wavesurfer/issues/15#issuecomment-83550051>
> .
>


-- 
Sent from my phone

**Comment by adamltaylor** [comment]
Ahh, OK.  But presumably it still wouldn't have worked with daqmx 14, because that's a known issue with DABS.

**Comment by adamltaylor** [comment]
We now think this issue is the same overlaps with

https://github.com/JaneliaSciComp/Wavesurfer/issues/52

which gave the same error message.  And indeed, Ben had Matlab installed on a non-C drive when that first occurred.
