### ISSUE TITLE
trial duration not loaded properly in open protocol

### ISSUE THREAD

**Issue by bjarthur** [JaneliaSciComp/Wavesurfer#16]
steps to reproduce:

1. save a protocol for which the trial duration is set to 2 seconds
2. quit wavesurfer, relaunch it, and open the protocol
3. note that the trial duration box has a 2 in it
4. click on display enabled and then play an acquisition
5. note that the white line in the green & black display only extends to 1 second

**Comment by bjarthur** [comment]
moreover...

6. hit enter in the trial duration box (there is already a 2 there)
7. play an acquisition again
8. note that now the white line extends to 2 seconds

**Comment by adamltaylor** [comment]
Fixed in develop branch, commit 2579c163cf16c55c73b3deafaf8ba1b27e0fdb76.
