### ISSUE TITLE
Manual needs to cover ws.loadDataFile()

### ISSUE THREAD

**Issue by adamltaylor** [JaneliaSciComp/Wavesurfer#161]
Present in 0.918 manual

**Comment by adamltaylor** [comment]
A user in the field mentioned this in an e-mail.

**Comment by noahpettit** [comment]
Second this. I don't see it in 0.919 Manual.

**Comment by adamltaylor** [comment]
Fixed in 0.945 manual:

http://wavesurfer.janelia.org/manual-0.945/index.html#reading-acquired-data
