### ISSUE TITLE
Clock used in example user class doesn't exist in R2013b

### ISSUE THREAD

**Issue by davidackerman** [JaneliaSciComp/Wavesurfer#180]
For release 0.918:

Undefined function or variable 'datetime'.

Error in ws.examples.ExampleUserClass/startingRun (line 39)
            self.TimeAtStartOfLastRunAsString_ = datestr( datetime() ) ;

Error in ws.UserCodeManager/invoke (line 115)
                    self.TheObject_.(eventName)(rootModel, eventName, varargin{:});

Error in ws.WavesurferModel/callUserMethod_ (line 1900)
            self.UserCodeManager.invoke(self, eventName, varargin{:});

Error in ws.WavesurferModel/run_ (line 1177)
            self.callUserMethod_('startingRun');  

Error in ws.WavesurferModel/play (line 369)
            self.run_() ;

Error in ws.WavesurferMainController/play (line 125)
                self.Model.play();

Error in ws.WavesurferMainController/PlayButtonActuated (line 1973)
            self.play();

Error in ws.Controller/controlActuated (line 332)
                        self.(methodName)(source,event);

Error in ws.MCOSFigure/controlActuated (line 477)
                self.Controller_.controlActuated(controlName,source,event);

Error in ws.WavesurferMainFigure>@(source,event)(self.controlActuated(propertyName,source,event)) (line 541)
                        set(propertyThing,'Callback',@(source,event)(self.controlActuated(propertyName,source,event)));

**Comment by adamltaylor** [comment]
Fixed in develop in commit fccc7bd6936078bc18787aeb3ed1d689c44ddabc.
