### ISSUE TITLE
When do run with inf number of 1 sec sweeps, and stop in middle, get error

### ISSUE THREAD

**Issue by adamltaylor** [JaneliaSciComp/Wavesurfer#187]
The error shows up in a dialog box, with text "Expected message name looperReadyForSweep, got message name looperStoppedRun.

After, any attempt to start a run yields message such as "The refiller encountered a problem while getting ready for the run: Expected message name refillerReadyForRunOrPerhapsNot, got message name refillerReadyForSweep."  This effectively renders WS unusable.

This is in 0.9192, and in develop branch, commit 0e43052a6415946a4137bd92826619afa2256d59.

**Comment by davidackerman** [comment]
Can reproduce this with arbitrary number of 1 sec sweeps. Seems to occur when hitting "stop" stops the sweep at 1s.
<img width="1022" alt="stoppingsweeperrormessage" src="https://cloud.githubusercontent.com/assets/19193291/16284387/e5918670-389e-11e6-819b-c61b85cdedaf.png">

 This is in version 0.9192, and in develop branch, commit 2dd5e8d7d98847a7cbd09c2a17d005d99b4e9c60

**Comment by adamltaylor** [comment]
Fixed in develop branch as of commit 8d898c39edd0fe924d8782691b1cba8870e89512
