### ISSUE TITLE
support for digital quadrature input

### ISSUE THREAD

**Issue by bjarthur** [JaneliaSciComp/Wavesurfer#19]
this would be more accurate than integrating magee's velocity sensor.

http://zone.ni.com/reference/en-XX/help/370471W-01/daqmxcfunc/daqmxcreatecilinencoderchan/

**Comment by adamltaylor** [comment]
The more I think about it, the more I think we should implement this by acquiring the raw cosine-is-positive and sine-is-positive signals as (preferably digital) timed inputs, and computing the current counter value in the user hook function.  This should be easy to implement, and fits comfortably within the current WS framework.  Adding support for counter input channels would certainly be nice, but is also a much larger undertaking.  Implementing this in a user hook function would also potentially allow you to wait for the animal to do a full lap, then estimate the position at any point in time using both the past and the future of the cosine-is-positive, sine-is-positive, and the three photodiode signals.  Such an approach would, for instance, allow you to guarantee continuity of the estimated position vs time.
