### ISSUE TITLE
loadDataFile is not compatible with some older Wavesurfer versions

### ISSUE THREAD

**Issue by davidackerman** [JaneliaSciComp/Wavesurfer#192]
In older versions of Wavesurfer, the output does not include channel scaling coefficients which leads to an error when using loadDataFile. It would be better if loadDataFile were backward compatible.

**Comment by adamltaylor** [comment]
We should discuss this before anything drastic is done.

Adam

**Comment by adamltaylor** [comment]
Decided not to do anything about this.  We *want* ws.loadDataFile() to fail if it can't be done right.
