### ISSUE TITLE
support for arbitrary waveforms stored in files as stimuli

### ISSUE THREAD

**Issue by bjarthur** [JaneliaSciComp/Wavesurfer#20]
i need this for testing purposes, and natural vocalization (e.g. birdsong) people would find it useful too.

**Comment by adamltaylor** [comment]
Yes.  When implemented, should include logic to resample the source waveform to the current stimulation samping rate.

**Comment by adamltaylor** [comment]
Implemented by Ben.  Merged into develop as of commit 812f1ec58ca415f408efb0aebc16cfd96ed27f3d.
