### ISSUE TITLE
Display Update Rate thresholded to 10Hz??

### ISSUE THREAD

**Issue by wsphillips** [JaneliaSciComp/Wavesurfer#220]
Is there a reason for this? Gap-free/continous mode has enough stutter at 10Hz to cause eye strain. Would performance take a serious dive if it were increased to 30-60Hz (i.e. closer to monitor refresh rate)?

**Comment by adamltaylor** [comment]
We need to leave time to do logging, and optionally run user code.  And we want the UI to stay responsive in case the user wants to stop the run.  That's why that limit is there.
