### ISSUE TITLE
Issues with using looper to set the digital channel state when untimed in samplesAquired()

### ISSUE THREAD

**Issue by TuMengyu95** [JaneliaSciComp/Wavesurfer#230]
**function**        samplesAcquired(self, looper, eventName, analogData, digitalData) 
                    v = analogData( : ,self.ElectrodeChannel) ;
                    newValue = any(v>=self.SpikeThreshold) ;
                    looper.setDigitalOutputStateIfUntimedQuicklyAndDirtily(newValue) ;
**end**

Why does this alone not change the Digital Output State to 1 or 0 depending on the newValue?

I can do the change using     wsModel.DOChannelStateIfUntimed    in "dataAvailable" function in the frontend. But would prefer the setting of DO Channel state to be done in looper cos I need to implement feedback loop with minimum latency.

Thanks in advance!

**Comment by adamltaylor** [comment]
That should work.  Would you please e-mail me at taylora@janelia.hhmi.org with:

The version of Matlab you're using.
The version of WaveSurfer you're using.
The model of NI board you're using.
Your user class .m file.

Thanks,
Adam
