### ISSUE TITLE
Can samplesAcquired( ) in Looper be used to output a sound together with Data Acquisition Toolbox Matlab?

### ISSUE THREAD

**Issue by TuMengyu95** [JaneliaSciComp/Wavesurfer#232]
**function** samplesAcquired (self, looper, eventName, analogData, digitalData)
v = analogData ( : , 1);
**if** any (v<0)
           looper.setDigitalOutputStateIfUntimedQuicklyAndDirtily (1)
           queueOutputData ( self.session, self.data)     **%queue sound data for output to speakers** 
           startBackground ( self.session )                   **%output sound duration is 100 ms**
**else**
           looper.setDigitalOutputStateIfUntimedQuicklyAndDirtily (0)
**end**
**end**

**I was able to use**
          **queueOutputData ( self.session, self.data)  
          startBackground ( self.session )**
**to output sound with the **dataAvailable ( ) function.**** 

**With Looper, queueOutputData or startBackground seemed to not have been executed.**  Anyone knows why? 
Is it because the samplesAcquired( ) is called a few ms and cannot output a sound of 100 ms?
Is there a way to deliver a sound stimulus of 100 ms with Looper? The frequency I need to output a sound is at most 4 Hz.

Thanks in advance for your suggestions!

**Comment by adamltaylor** [comment]
I re-asked this question for you on the WaveSurfer Google Group (https://groups.google.com/forum/#!topic/wavesurfer/DgYbJCMvlMg).  I think that's probably a better place for this kind of question.
