### ISSUE TITLE
More than one digital input channel

### ISSUE THREAD

**Issue by horsto** [JaneliaSciComp/Wavesurfer#233]
Hi Adam, 
I am just getting started with wavesurfer and I am using it to log frame times from a camera and a microscope in parallel. I am recording these signals on two digital input channels from a PCIe-6363 card. When I plot the recorded digital sweep time stamps I get the following pattern (black trace): 
<img width="1165" alt="start of acquisition" src="https://user-images.githubusercontent.com/7548928/39883258-97653bf8-5486-11e8-8a6e-d5de11b84617.png">
I am detecting the status of each recorded digital input by solving the combination of inputs that occur over time (0,1,2 or 3). Is there an easy way (that I am overlooking) of making sense of this data, meaning - can I extract the status of each line at each time point in a generalized way (even if I have more than 2 channels recorded for example)?

**Comment by adamltaylor** [comment]
I think you want to use the bitget() function in Matlab (or something equivalent in Python) to extract the individual bits from that signal.  WaveSurfer multiplexes multiple digital inputs onto a single uint8 (in your case).  So you want to extract the individual bits from each uint8 value at each time point.  [Here](https://www.mathworks.com/help/matlab/ref/bitget.html)'s the documentation of bitgit, if that helps.

**Comment by horsto** [comment]
Thanks, great, that did the trick! 
Just as a reference: I am using [numpy unpackbits](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.unpackbits.html) in python.
