### ISSUE TITLE
Support for NI USB device

### ISSUE THREAD

**Issue by horsto** [JaneliaSciComp/Wavesurfer#234]
I have a NI USB-6211 device that I want to use for acquiring signals via wavesurfer. Are these kind of devices supported? I can select it in wavesurfer, but when I try to start a sweep it tells me the PFI8 (trigger) is not recognized. Is there a workaround for that?

**Comment by adamltaylor** [comment]
No, that's an M series device, not an X series, so is not supported.  Sorry...
