### ISSUE TITLE
The path detect method is bad. (e.g. nidaqmx.h)

### ISSUE THREAD

**Issue by sppmg** [JaneliaSciComp/Wavesurfer#237]
Hi
Thanks your wavesurfer.

I get error:

```
Error using ws.most.APIWrapper/extractCodeMap (line 910)
The file 'D:\program files (x86)\national instruments\ni-daq\daqmx ansi c dev\include\nidaqmx.h' was not
found or could not be opened.
```

After long time research, I find problem code in `+ws/startPath.m:` and `+ws/+most/+idioms/startPath.m:`

And my NI driver install in `C:\` but Matlab install in `D:\` , that cause this error.

Maybe you can check file exist first, and use `uigetdir` to select path if it's non-exist. After that, save the path to config file.

**Comment by adamltaylor** [comment]
Thank you for the bug report, and for your debugging efforts!
