### ISSUE TITLE
Problem of `User Code` include DAQ code

### ISSUE THREAD

**Issue by sppmg** [JaneliaSciComp/Wavesurfer#239]
Hi

In my experiment will use `MultiClamp` with `Wavesufer`, and use another matlab program to control experiment .

If I load code manually (click menu then type name) ,it woke fine. but if I save in `Protocol`, `WS` will error after load protocol about DAQ already using (and that protocol can't remove user code because must load first ..... ) .

Look like it cause by `WS` run user code early then itself ? 

Any ideal to fix it?

---------

And another question, Does `WS` occupy all channel in `Primary Device` ? Can I use idle channel in my control program ?

Thanks.

**Comment by adamltaylor** [comment]
Please send me your protocol file and user class .m file at taylora@janelia.hhmi.org, and I will try to help.  Also, please tell me what version of WaveSurfer you are using.

You can only have one AI task per device in DAQmx, so I don't think that you will be able to use idle AI channels in your control program.  Using idle DIO lines may work, depending on what you're doing.
