### ISSUE TITLE
Parsing values from StimulusLibrary in a custom class

### ISSUE THREAD

**Issue by pratikmistry08** [JaneliaSciComp/Wavesurfer#243]
At the end of each sweep, the post-doc in our lab is using a stimulus called test.

I'm trying to retrieve these values in a customized class, but I'm having a difficult time getting values, such as delay, duration, and amplitude. (Not sure what the correct syntax is for retrieving these values).

**Comment by adamltaylor** [comment]
Moved this over to:

https://groups.google.com/forum/#!topic/wavesurfer/LCU1Cq3t8Dw
