### ISSUE TITLE
Feature request - would it be possible to use non X-series NI devices?

### ISSUE THREAD

**Issue by liamstaras** [JaneliaSciComp/Wavesurfer#248]
Great software - seems like a very stable open source alternative to popular proprietary solutions. I believe it could truly dominate all corners of the electrophys market if it supported the lower-cost NI devices by providing a featureful system for all budgets and setups! What steps would be required to achieve this?

**Comment by adamltaylor** [comment]
Sorry, but there is currently no funding available to make this happen.
