### ISSUE TITLE
Acquire data from DIO "banks" P1 and P2?

### ISSUE THREAD

**Issue by brandonStell** [JaneliaSciComp/Wavesurfer#251]
From the WaveSurfer documentation:

> NI DAQ devices typically have three “banks” of digital I/O terminals, called “P0”, “P1”, and “P2”. For instance the first DIO terminal in bank P0 is called “P0.0”, the second is called “P0.1”, etc. Only terminals in bank P0 can be used as digital inputs in WaveSurfer. 

Would it be possible to access the other NI banks from WaveSurfer?

**Comment by adamltaylor** [comment]
You can use the other banks as triggers, but not digital I/O channels.

**Comment by brandonStell** [comment]
Thanks for the quick reply.  Do you suggest another solution if we need to record from more than 10 I/O channels?
