### ISSUE TITLE
If Matlab thread is very busy, data available callbacks get dropped silently

### ISSUE THREAD

**Issue by adamltaylor** [JaneliaSciComp/Wavesurfer#43]
Because of some of the complexities of handling callbacks from DAQmx in Matlab, it seems that if the Matlab main computational thread is going at 100%, the dabs.ni.daqmx data available callback will get dropped with no kind of error or warning.  We've never definitively seen this in WS, but it is possible to elicit in a test bed script.  It doesn't seem to happen when acquiring at 20 kHz, with no data available user hook function, but we worry that at higher acquisition rates, with a computationally intensive data available user function, it could.  One solution would be to call toc() in the data available callback, and check that it hasn't been much longer than the expected interval.  Another would be to not use dabs.ni.daqmx callbacks at all, but have WS poll for data on a Matlab timer.

As of relase 0.775

**Comment by bjarthur** [comment]
here's how NI recommends getting software timestamps:
http://digital.ni.com/public.nsf/allkb/354468202721D85D8625759F004B0357

**Comment by adamltaylor** [comment]
As of commit 8946276506cbd3ac28f5aac41b0dd13024bdce9d on the develop branch, WS no longer uses the dabs.ni.daqmx callbacks.  Instead, it uses a Matlab timer object to poll for new data and to check when tasks complete.  Matlab timers have their issues, but generally I feel better not relying on the dabs.ni.daqmx callbacks.
