### ISSUE TITLE
NTimesSamplesAcquiredCalledSinceExperimentStart == 2 to start with

### ISSUE THREAD

**Issue by bjarthur** [JaneliaSciComp/Wavesurfer#65]
it used to be the case that the first time the data available user function was called, NTimesSamplesAcquiredCalledSinceExperimentStart was 1, now it is 2.  this is on the develop branch, cbff01 commit.

examples/rasterContinuous will need updated once fixed.

**Comment by adamltaylor** [comment]
Changing this would make the variable name misleading, and with user hook classes there are now better ways for user code to determine whether the current call to dataAvailable is the first in an experiment.
