### ISSUE TITLE
WS is slow to start with four Heka electrodes

### ISSUE THREAD

**Issue by adamltaylor** [JaneliaSciComp/Wavesurfer#81]
Partly because of the time to query all the electrodes to get their state.

Minoru suggests not doing this check if the user has the softpanel turned off, which makes sense.

**Comment by adamltaylor** [comment]
Hidehiko reiterated that this is important.  Need to profile to be sure, but may need to add a checkbox to turn off the pre-start amplifier query.  (For both test pulse and normal start.)

**Comment by davidackerman** [comment]
Checkbox added to provide option to turn off pre-start amplifier query. Issue closed as of commit 2dd5e8d7d98847a7cbd09c2a17d005d99b4e9c60
